List newArrivalsFoodList = [
  {
    'image': "assets/biriyani.jpg",
    'categori': "Biriyani",
    'name': "Kacci Biriyani",
    'discount percent': "-54%",
    'Price': "\$50.00",
    'discount price': "\$19.50",
    'rating': "3.6",
    'favorite': true,
  },
  {
    'image': "assets/Sandwich.jpg",
    'categori': "Burger",
    'name': "Chicha Burger",
    'discount percent': "-54%",
    'Price': "\$50.00",
    'discount price': "\$19.50",
    'rating': "3.6",
  },
  {
    'image': "assets/sauces.jpg",
    'categori': "Drinks",
    'name': "Tomoto Juice",
    'discount percent': "-54%",
    'Price': "\$50.00",
    'discount price': "\$19.50",
    'rating': "3.6",
  },
  {
    'image': "assets/pizza.jpg",
    'categori': "Pizza",
    'name': "Neapol Pizza",
    'discount percent': "-54%",
    'Price': "\$50.00",
    'discount price': "\$19.50",
    'rating': "3.6",
  },
  {
    'image': "assets/sweet.jpg",
    'categori': "Sweet",
    'name': "Golap Jamon",
    'discount percent': "-54%",
    'Price': "\$50.00",
    'discount price': "\$19.50",
    'rating': "3.6",
  },
  {
    'image': "assets/food1.jpg",
    'categori': "Drink",
    'name': "Deshi Juice",
    'discount percent': "-54%",
    'Price': "\$50.00",
    'discount price': "\$19.50",
    'rating': "3.6",
  },
];
